### ISSUE TITLE
Feature Request: Find/Replace in NoScribe Editor

### ISSUE THREAD

**Issue by glocalglocal** [kaixxx/noScribe#101] opened 2024-11-10 16:01 UTC
Find (and Replace) would significantly improve the usability of NoScribe Editor when correcting or simply locating text. As a workaround, I open a file in a text editor, sometimes while working with NoScribe Editor on the same file, for Find/Replace which is not great.

**Comment by kaixxx** [comment] 2024-11-11 09:58
Yes, I agree. It's already on my list. Good to hear that other people miss this feature too. Thank you!

**Comment by BabyFnord** [comment] 2024-11-23 20:03
+1 very much missed!

**Comment by kaixxx** [comment] 2024-12-02 12:53
Closing this because it is a duplicate of: https://github.com/kaixxx/noScribe/issues/96
But I will definitely try to implement this function in the next release!

**Closed by kaixxx** 2024-12-02 12:53 UTC
Labels: enhancement
